#!/usr/bin/env sh

export XDG_CURRENT_DESKTOP="river"
export XDG_SESSION_DESKTOP="river"
export XDG_SESSION_TYPE="wayland"
export DESKTOP_SESSION="river"

export MOZ_ENABLE_WAYLAND="1"
export MOZ_DBUS_REMOTE="1"

export GDK_BACKEND="wayland,x11"
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland,x11"
export _JAVA_AWT_WM_NONREPARENTING="1"

exec river "$@"
