#!/usr/bin/env sh

export XDG_CURRENT_DESKTOP="river"
export XDG_SESSION_DESKTOP="river"
export XDG_SESSION_TYPE="wayland"
export DESKTOP_SESSION="river"

export MOZ_ENABLE_WAYLAND="1"

export GDK_BACKEND="wayland,x11"
export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME="qt6ct"

export GTK_THEME="Adwaita:dark"

exec river "$@"
